# Generated by Django 4.2.7 on 2023-11-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
